// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrb239iV3DxEwbf1trBKCp0ka7gRC3oY',
    appId: '1:317467092059:android:705dce7ccab9c55e2a4b7e',
    messagingSenderId: '317467092059',
    projectId: 'datesim-4a434',
    storageBucket: 'datesim-4a434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYcqEyqyMUj8eRb-Q0zk9XDJ8Zf0T9XLY',
    appId: '1:317467092059:ios:dbf4ff6cc396c2e92a4b7e',
    messagingSenderId: '317467092059',
    projectId: 'datesim-4a434',
    storageBucket: 'datesim-4a434.firebasestorage.app',
    iosBundleId: 'com.datesim.datesim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFbEM3aB88zMCbPcg2FP4QU1FVsuvIRE',
    appId: '1:317467092059:web:3ed338a3b8cba7342a4b7e',
    messagingSenderId: '317467092059',
    projectId: 'datesim-4a434',
    authDomain: 'datesim-4a434.firebaseapp.com',
    storageBucket: 'datesim-4a434.firebasestorage.app',
    measurementId: 'G-E6J3YP689K',
  );
}
